# Generated by Django 2.2.24 on 2021-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_date_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Public key'),
        ),
        migrations.AddField(
            model_name='user',
            name='threebot_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Threebot name'),
        ),
    ]
